# Install packgages to help you get started with Actions

library(censusapi)
library(jsonlite)
library(httr)
library(dplyr)
library(magrittr)

# Find what kind of data you would like to pull

r<-GET("https://min-api.cryptocompare.com/data/v2/histoday?fsym=BTC&tsym=USD&limit=30&e=CCCAGG")


  # Allows you to information about the content
  
 headers(r)
str(content(r))
http_status(r)
r$status_code
names(r)


# Get content
text_content <- content(r,"text",encoding = "UTF-8")
text_content

  # Parse with Jsonlite
json_content <- text_content %>% fromJSON()
json_content
data.1 <-json_content$Data$Data
data.1$count

    # Calculate Daily Rates
    
  data.1$daily_percentage <- c(((data.1$open-data.1$close)/data.1$open)*100)
  data.1$daily <- c(data.1$daily/100)

   
   # Plot a chart for the Bitcoin price and its hashrate in a dual axis chart, making sure the x-axis is in date format
   
   
   k<- GET("https://min-api.cryptocompare.com/data/blockchain/histo/day?fsym=BTC&limit=30&api_key=bf821d4ece66d7f596bf4554c1423ca0a1b534f830883b7dba5e26905cebfdfc")
    #(data for Bitcoin for the last 30 days,different link has been used)
   
k$status_code
text_content <- content(k,"text",encoding = "UTF-8")
json_content <- text_content %>% fromJSON()
json_content
data.2 <-json_content$Data$Data

data.1<- data.1[-c(31), ]

#convert this POSIXct to the Date class as shown below:


mydates = data.1$time
class(mydates) = c('POSIXct')
 mydates
class(mydates)

data.1$time<-mydates


mydates2 = data.2$time
class(mydates2) = c('POSIXct,POSIXt')
mydates
class(mydates2)

data.2$time<-mydates

#Merging data

total <- merge(data.1,data.2,by="time")


Plot of correlation of price and hashrate 

#install dplyr,patchwork,latticaextra

library(ggplot2)
library(dplyr)
library(patchwork) 
library(hrbrthemes)

class(total$time) = c('POSIXct,POSIXt')



obj1 <- xyplot(total$close ~ total$time, total, type = "l" , lwd=2,main="Hashrate vs Price",
               xlab="Dates",
               ylab="Price")
obj2 <- xyplot(total$hashrate ~ total$time , total, type = "l", lwd=2,xlab="Hashrate",
               ylab="Hashrate")

doubleYScale(obj1, obj2,text = c("Price", "Hashrate"), add.ylab2 = TRUE, use.style=TRUE )




mydates2 = data.2$time
class(mydates2) = c('POSIXct,POSIXt')
mydates
class(mydates2)

mydates1 = data.1$time
class(mydates1) = c('POSIXct,POSIXt')
mydates
class(mydates1)

mydates3 = total$time
class(mydates3) = c('POSIXct,POSIXt')
mydates
class(mydates3)

total$time <- as.Date(total$time)
total$time <- format(total$time, "%d-%b-%Y")

#Download the Data
write.csv(data.1,"DATA1.csv",row.names = FALSE)
write.csv(data.2,"DATA2.csv",row.names = FALSE)  




